# Generated by Django 4.0.2 on 2022-03-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_menu_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageslider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='imageslider/')),
            ],
        ),
    ]
