# Generated by Django 4.0.2 on 2022-03-18 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_imageslider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageslider',
            name='image',
            field=models.ImageField(upload_to='project/image/imageslider/'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='project/image/imageproduct/'),
        ),
    ]
